services:
  # API-based service - uses OpenAI API
  api-service:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8001:8000"
    environment:
      - SERVICE_TYPE=api
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
    volumes:
      - ./config/api_config.yaml:/app/config.yaml:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Self-hosted service - local model
  selfhosted-service:
    build:
      context: .
      dockerfile: Dockerfile.selfhosted
    ports:
      - "8002:8000"
    environment:
      - SERVICE_TYPE=selfhosted
      - MODEL_NAME=facebook/bart-large-cnn
      - LOG_LEVEL=INFO
    volumes:
      - ./config/selfhosted_config.yaml:/app/config.yaml:ro
      - model_cache:/app/models  # Cache models between restarts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s  # Model loading takes time
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G

  # Load balancer to demonstrate routing
  nginx-lb:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-service
      - selfhosted-service
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M

  # Performance testing container
  performance-tester:
    build:
      context: .
      dockerfile: Dockerfile.tester
    environment:
      - API_SERVICE_URL=http://api-service:8000
      - SELFHOSTED_SERVICE_URL=http://selfhosted-service:8000
    volumes:
      - ./test_results:/app/results
    depends_on:
      - api-service
      - selfhosted-service
    profiles:
      - testing  # Only run when explicitly requested
    deploy:
      resources:
        limits:
          memory: 512M

  # Basic monitoring for resource usage
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  model_cache:  # Persist downloaded models
  portainer_data:
  test_results:
