service_name: "Self-hosted Summarization"
model_name: "facebook/bart-large-cnn"
max_length: 150
min_length: 50
device: "cpu"  # cpu or cuda
cache_dir: "/app/models"

performance:
  expected_latency_ms: 100
  expected_memory_mb: 2500
  expected_startup_seconds: 45

cost:
  model: "fixed"
  estimated_monthly: 500
